version: "3.7"
services:
  external-auth:
    image: external-auth:1.0-SNAPSHOT
    ports:
    - "8080:8080"
    - "50051:50051"

  ratelimit:
    image: ratelimit-service:1.0-SNAPSHOT
    ports:
    - "50052:50052"

  envoyproxy-websocket:
    build:
      context: .
      dockerfile: ./envoy_resources/Dockerfile
    ports:
    - "9095:9095"
    - "9000:9000"




